In [13]:
import numpy as np

In [14]:
a=np.array([1,2,3])

In [15]:
a

array([1, 2, 3])

In [16]:
b=np.array([[0,3,54,6,7,8],[5,6,7,8,10]])

<ipython-input-16-665e4863c96b>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  b=np.array([[0,3,54,6,7,8],[5,6,7,8,10]])


In [17]:
b

array([list([0, 3, 54, 6, 7, 8]), list([5, 6, 7, 8, 10])], dtype=object)

In [18]:
b.shape()

TypeError: 'tuple' object is not callable

In [19]:
b.shape

(2,)

In [25]:
a.dtype

dtype('int32')

In [26]:
# GETTING the item size 

In [28]:
a.itemsize

4

In [30]:
a.nbytes

12

In [45]:
c=np.array([[1,2,4,5,6,7],[8,9,10,11,12,13]])

print(c)

[[ 1  2  4  5  6  7]
 [ 8  9 10 11 12 13]]


In [48]:
c[1,-4]

10

In [49]:
c[0,:]

array([1, 2, 4, 5, 6, 7])

In [50]:
c[1,:]

array([ 8,  9, 10, 11, 12, 13])

In [51]:
c[:,2]

array([ 4, 10])

In [52]:
c[1,2:]

array([10, 11, 12, 13])

In [54]:
c[0,-1:2]

array([], dtype=int32)

In [55]:
# understanding the statistics approach

In [56]:
stats=np.array([[1,2,3],[4,5,6]])

In [57]:
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
np.min(stats,axis=1)

array([1, 4])

In [61]:
np.max(stats)

6

In [62]:
#vertically stacking vectors 

In [63]:
v1=np.array([1,2,3,4])

v2=np.array([5,6,7,8])

In [65]:
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [67]:
h1=np.ones((1,4))

In [69]:
h2=np.zeros((3,4))

In [70]:
print(h1,h2)

[[1. 1. 1. 1.]] [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [82]:
np.hstack((h1,h2))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 1 and the array at index 1 has size 3

In [73]:
#Load data from file load data , Mscellimious

In [89]:
filedata=np.genfromtxt('Desktop/data.txt',delimiter=',')

filedata.astype('int32')

array([[ 1,  2,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [90]:
filedata

array([[ 1.,  2.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
       [13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.]])

In [91]:
#Advances indexing

In [95]:
np.any(filedata >20,axis=0)

array([False, False, False, False, False, False, False, False,  True,
        True,  True])

In [96]:
(~(filedata >20)&(filedata <10))

array([[ True,  True,  True,  True,  True,  True,  True,  True, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False]])

In [98]:
np.identify(6)

AttributeError: module 'numpy' has no attribute 'identify'

In [104]:
r1=np.repeat(3,axis=0)

TypeError: _repeat_dispatcher() missing 1 required positional argument: 'repeats'

In [105]:
arr=np.array([[1,2,3]])

In [107]:
r1=np.repeat(arr,1,axis=0)

In [108]:
print(r1)

[[1 2 3]]


In [109]:
output=np.ones([5,5])

In [110]:
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [111]:
z=np.zeros([3,3])

In [113]:
z[1,1]=9

In [114]:
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [116]:
output,z 

(array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]),
 array([[0., 0., 0.],
        [0., 9., 0.],
        [0., 0., 0.]]))

In [119]:
a=np.array([1,2,3])

b=a.copy()

In [121]:
b=100

In [122]:
print(b)

100


In [123]:
print(b)

100


In [125]:
#Linear algebra

In [126]:
a=np.ones((1,2,3))

In [127]:
print(a)

[[[1. 1. 1.]
  [1. 1. 1.]]]


In [128]:
b=np.full((3,2),2)

In [129]:
print(b)

[[2 2]
 [2 2]
 [2 2]]


In [130]:
np.matmul(a,b)

array([[[6., 6.],
        [6., 6.]]])

In [132]:
# Finding determinant

In [134]:
c=np.identity(3)

In [136]:
np.linalg.det(c)

1.0